Reintroduce tags check

diff --git a/.github/workflows/tags.yaml b/.github/workflows/tags.yaml
--- a/.github/workflows/tags.yaml
+++ b/.github/workflows/tags.yaml
@@ -37,6 +37,14 @@ jobs:
           ref: ${{ steps.extract-ref.outputs.ref }}
           fetch-depth: 0
 
+      - name: Check version tag
+        run: |
+          if git tag --points-at HEAD | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
+            exit 0
+          fi
+          echo "ERROR: There needs to be a version tag."
+          exit 1
+
   update-package:
     name: Update package
     runs-on: ubuntu-latest
